version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: nodeUsers
      MYSQL_USER: sa
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
